### PR TITLE
Implement Uniswap AMM

### PR DESCRIPTION
**Pull request by gbear605**
Implements an automated market maker using the basic Uniswap algorithm from https://manifoldmarkets.notion.site/Maniswap-ce406e1e897d417cbd491071ea8a0c39.

Currently branched off of https://github.com/casesandberg/play-money/pull/10, so it will need a rebase after that is finished and merged in.

### CODE REVIEW

**Comment by gbear605** [comment]
One thing that this didn't try to address, but will need to be handled soon, is that the AMM amounts are floats. I think ideally all money should be integer (or perhaps, fixed point decimal).

**Comment by casesandberg** [comment]
> One thing that this didn't try to address, but will need to be handled soon, is that the AMM amounts are floats. I think ideally all money should be integer (or perhaps, fixed point decimal).

Yeah, likely we want to be using a special decimal datatype instead of number. I did a little digging and decimal.js and bignumber.js seem to be well maintained and pretty popular. Heres a wiki about the differences of them: https://github.com/MikeMcl/big.js/wiki

**Comment by casesandberg** [comment]
This looks great!!

**Comment by casesandberg** [comment]
Closes https://github.com/casesandberg/play-money/issues/18

**Pull request merged**
